# Generated by Django 2.2 on 2020-08-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='analytics', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_id',
            field=models.IntegerField(),
        ),
    ]
