# Generated by Django 2.2 on 2020-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200816_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='sname',
            field=models.CharField(max_length=20),
        ),
    ]
