# Generated by Django 2.2 on 2020-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200816_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='qid',
            field=models.IntegerField(),
        ),
    ]
