# Generated by Django 2.2 on 2020-08-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200816_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='qid',
        ),
    ]
